sonar.projectKey=JavaFX_TicTacToe-cse566
sonar.sources=src
# Point this to where your IDE puts compiled files (usually 'bin' or 'out')
sonar.java.binaries=bin
# If you don't have a bin folder, leave it blank or use '.'
